title: <p align="center"> Charles Uwagboe </p>

logo: "/images/circle-removebg-preview.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/charlesuwagboe/">LinkedIn</a> |
  <a href="https://github.com/charlesuwagboe">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Business Analytics at Simon Business School, University of Rochester.
  <br><br>
  I am currently a Machine Learning Research Intern at Skim AI Technologies with a focus on NLP and Deep Learning research.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-0WM2RYHGPR # Google Analytics tracking ID
